services:
  postgres-dev:
    image: pgvector/pgvector:pg15
    container_name: chatbot-postgres-dev
    environment:
      POSTGRES_DB: chatbot_dev
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user -d chatbot_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  default:
    name: chatbot-network
