# Generated by Django 5.2.6 on 2025-10-01 10:24

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "strategy_name",
                    models.CharField(
                        help_text="RAG strategy identifier (e.g., 'baseline', 'hybrid')",
                        max_length=100,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Strategy configuration parameters"
                    ),
                ),
                (
                    "traffic_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of traffic allocated (0.00-100.00)",
                        max_digits=5,
                    ),
                ),
                (
                    "target_languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        help_text="Limit experiment to specific languages (e.g., ['en', 'de'])",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "target_document_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        help_text="Limit to specific document types",
                        null=True,
                        size=None,
                    ),
                ),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_responses", models.IntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(blank=True, null=True)),
                ("avg_cost_usd", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "traffic_percentage"],
                        name="core_experi_status_1f3ac9_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_experi_created_216697_idx"
                    ),
                ],
            },
        ),
    ]
