# Generated by Django 5.2.6 on 2025-10-02 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Flag identifier (e.g., 'USE_PGVECTOR')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, help_text="Global on/off switch"
                    ),
                ),
                (
                    "rollout_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of users to enable (0-100). Only applies if enabled=True",
                        max_digits=5,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this flag controls"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "enabled"], name="core_featur_name_7e1179_idx"
                    )
                ],
            },
        ),
    ]
