# Generated by Django 5.2.6 on 2025-09-25 11:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="documents/")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("datasheet", "Datasheet"),
                            ("firmware_notes", "Firmware Notes"),
                            ("quick_start", "Quick Start Guide"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("product_line", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("section_title", models.CharField(blank=True, max_length=255)),
                ("chunk_index", models.PositiveIntegerField()),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
